---
- hosts: apache
  tasks:
    - name: run echo command
      command: echo hello bob   #command module

    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest  #APT module

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
  
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
